version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: obesity_predictor/ci_cd/docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - PYTHONUNBUFFERED=1
    depends_on:
      - mlflow

  app:
    build:
      context: .
      dockerfile: obesity_predictor/ci_cd/docker/Dockerfile.app
    ports:
      - "8501:8501"
    depends_on:
      - api

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - MLFLOW_ARTIFACT_ROOT=/mlruns