# model_config.yaml
# =========================
# Centralized model hyperparameters and configuration
# for CatBoost, XGBoost, and LightGBM models.

catboost:
  iterations: 300
  learning_rate: 0.1
  depth: 6
  loss_function: "MultiClass"

xgboost:
  n_estimators: 400
  learning_rate: 0.1
  max_depth: 6
  objective: "multi:softmax"
  eval_metric: "mlogloss"

lightgbm:
  n_estimators: 400
  learning_rate: 0.1
  num_leaves: 31
  objective: "multiclass"
